### ISSUE TITLE
Failed to build the docker image

### ISSUE THREAD

**Issue by jpweng** [ffs221/docker-restApi-flask-mlModel#1]
When running docker build . -t image_name, in my windows 10 environment, I get this error:

 => ERROR [6/6] RUN ["pipenv", "install"]                                                                          3.0s
------
 > [6/6] RUN ["pipenv", "install"]:
#10 1.514 Creating a virtualenv for this project...
#10 1.514 Pipfile: /server/Pipfile
#10 1.528 Using /usr/local/bin/python3.7m (3.7.3) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.7.3.final.0-64 in 543ms
#10 2.201   creator CPython3Posix(dest=/root/.local/share/virtualenvs/server-CV4Qw303, clear=False, no_vcs_ignore=False, global=False)
#10 2.201   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
#10 2.201     added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
#10 2.201   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
#10 2.201
#10 2.254✔ Successfully created virtual environment!
#10 2.388 Virtualenv location: /root/.local/share/virtualenvs/server-CV4Qw303
#10 2.412 Pipfile.lock not found, creating...
#10 2.418 Locking [dev-packages] dependencies...
#10 2.418 Locking [packages] dependencies...
Building requirements...
#10 2.501Traceback (most recent call last):
#10 2.502   File "/usr/local/bin/pipenv", line 10, in <module>
#10 2.502     sys.exit(cli())
#10 2.502   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
#10 2.503     return self.main(*args, **kwargs)
#10 2.503   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 782, in main
#10 2.503     rv = self.invoke(ctx)
#10 2.503   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
#10 2.504     return _process_result(sub_ctx.command.invoke(sub_ctx))
#10 2.504   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
#10 2.505     return ctx.invoke(self.callback, **ctx.params)
#10 2.505   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
#10 2.505     return callback(*args, **kwargs)
#10 2.505   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
#10 2.505     return ctx.invoke(f, obj, *args, **kwargs)
#10 2.506   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
#10 2.506     return callback(*args, **kwargs)
#10 2.506   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
#10 2.506     return f(get_current_context(), *args, **kwargs)
#10 2.507   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 253, in install
#10 2.507     site_packages=state.site_packages
#10 2.507   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2063, in do_install
#10 2.508     keep_outdated=keep_outdated
#10 2.508   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1302, in do_init
#10 2.509     pypi_mirror=pypi_mirror,
#10 2.509   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1113, in do_lock
#10 2.509     keep_outdated=keep_outdated
#10 2.510   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 1333, in venv_resolve_deps
#10 2.510     deps, project, r=False, include_index=True
#10 2.510   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 1451, in convert_deps_to_pip
#10 2.511     new_dep = Requirement.from_pipfile(dep_name, dep)
#10 2.511   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2747, in from_pipfile
#10 2.512     r = FileRequirement.from_pipfile(name, pipfile)
#10 2.512   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1841, in from_pipfile
#10 2.512     arg_dict["parsed_line"] = Line(line)
#10 2.512   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 171, in __init__
#10 2.513     self.parse()
#10 2.513   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1301, in parse
#10 2.514     "Supplied requirement is not installable: {0!r}".format(self.line)
#10 2.514 pipenv.vendor.requirementslib.exceptions.RequirementError: Supplied requirement is not installable: 'file:///server/xgboost-1.2.1-cp37-cp37m-win32.whl#egg=xgboost'
------
executor failed running [pipenv install]: exit code: 1

**Comment by ffs221** [comment]
Hi, Thank you for your feedback.
I have just edited the pipFile.
I forgot to update it after my development.
Try it again and let me know how it goes!.

**Comment by jpweng** [comment]
Solved, thanks!
